key_file = "creds/intersight-cgascoig-20200423.pem"
key_id = "59c84e4a16267c0001c23428/59cc595416267c0001a0dfc7/5ea26d577564612d3025b892"
otel_collector_endpoint = "http://localhost:4317"

[[pollers]]
name = "virtual_machine_count"
api_query = "api/v1/virtualization/VirtualMachines?$count=true"
aggregator = "result_count"

[[pollers]]
name = "ntp_policy_count"
api_query = "api/v1/ntp/Policies?$count=true"
aggregator = "result_count"